name: test

on:
  push:
    branches: "*"
jobs:
  init:
    runs-on: ubuntu-latest
    name: Prepare
  
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "io"
          touch results/xxx
      
      - uses: EndBug/add-and-commit@v9
        with:
          add: "results"
          author_name: "DashlordBetaGouvBot"
          author_email: "DashlordBetaGouvBot@incubateur.net"
         # message: "update: ${{ matrix.sites.url }}"
      #    pull: '--rebase --autostash'
